# Generated by Django 4.0.4 on 2022-05-28 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='image',
            name='category',
        ),
        migrations.RemoveField(
            model_name='image',
            name='location',
        ),
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='section_name',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='image',
            name='section_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='galleria.category'),
        ),
        migrations.AddField(
            model_name='image',
            name='spot_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='galleria.location'),
        ),
        migrations.AddField(
            model_name='location',
            name='spot_name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
