# Generated by Django 4.0.4 on 2022-05-30 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['posted_date']},
        ),
    ]
