# Generated by Django 4.0.4 on 2022-05-28 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0003_image_posted_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='section_name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='section_name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='spot_name',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='spot_name',
            new_name='location',
        ),
    ]
