# Generated by Django 4.0.4 on 2022-05-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0005_alter_image_category_alter_image_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(max_length=60),
        ),
    ]
