# Generated by Django 4.0.4 on 2022-05-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0006_alter_category_category_alter_location_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='category',
        ),
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.ManyToManyField(to='galleria.category'),
        ),
    ]
