# Generated by Django 4.0.4 on 2022-05-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0008_alter_image_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['image_name']},
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='gallery/'),
        ),
    ]
